### ISSUE TITLE
python files can not executing 

### ISSUE THREAD

**Issue by AnimeWaifuGirl** [justchokingaround/jerry#32]
i get by any pythion script this message 

 python ./jerrydiscordpresence.py 
Traceback (most recent call last):
  File "/home/jan/jerry/./jerrydiscordpresence.py", line 6, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'

**Comment by justchokingaround** [comment]
`pip install httpx pypresence`

**Comment by AnimeWaifuGirl** [comment]
pipx: error: unrecognized arguments: pypresence

**Comment by AnimeWaifuGirl** [comment]
if you asked wich linux and environment i use! 
distro: Arch Linux
environment: FluxBox

**Comment by justchokingaround** [comment]
`\pip install --break-system-packages httpx pypresence`

ure not supposed to use pipx for this

**Comment by AnimeWaifuGirl** [comment]
now i got this error after the installation over pip was successfully!

[jan@archlinux jerry]$ ./jerrydiscordpresence.py 
Traceback (most recent call last):
  File "/home/jan/jerry/./jerrydiscordpresence.py", line 17, in <module>
    (
ValueError: not enough values to unpack (expected at least 7, got 1)

**Comment by justchokingaround** [comment]
ure supposed to use jerry itself not the python script, jerry will automatically send the necessary args to the python script

**Comment by justchokingaround** [comment]
closing due to inactivity
